[tool.poetry]
name = "mtlcm"
version = "0.1.0"
description = ""
authors = ["Julien Horwood, Wenlin Chen, Juyeon Heo"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
